// export const AUTHORIZE_REQUEST = "AUTHORIZE_REQUEST";
// export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
// export const GET_AUTH_USERS = "GET_AUTH_USERS";
// export const LOG_OUT = "LOG_OUT";

export const SET_SIGNUPBTN = 'SET_SIGNUPBTN';
export const LOADING = 'LOADING';
export const REGISTER_COMPANY = 'REGISTER_COMPANY';
export const REGISTER_USER = 'REGISTER_USER';
export const AUTHORIZE_SUCCESS = 'AUTHORIZE_SUCCESS';
export const LOGIN_USER = 'LOGIN_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const GET_AUTH_USERS = 'GET_AUTH_USERS';
export const GET_AUTH_USER = 'GET_AUTH_USER';
export const AUTHORIZE_FAIL = 'AUTHORIZE_FAIL';
export const CLEAR_USERS = 'CLEAR_USERS';
export const REMOVE_FOOTER = 'REMOVE_FOOTER';
export const USERS_EMAIL = "USERS_EMAIL";
export const VERIFY_BVN = "VERIFY_BVN";
export const VERIFY_BVN_SUCCESS = "VERIFY_BVN_SUCCESS";
export const VERIFY_BVN_ERROR = "VERIFY_BVN_ERROR";
export const CLOSE_MODAL = "CLOSE_MODAL"
export const CLEAR_MESSAGES = "CLEAR_MESSAGES"
//


// export const LOG_OUT = "LOG_OUT";
