// export const AUTHORIZE_REQUEST = "AUTHORIZE_REQUEST";
// export const LOGIN_USER = "LOGIN_USER";
// export const AUTHORIZE_FAIL = "AUTHORIZE_FAIL";
// export const LOG_OUT = "LOG_OUT";


export const SET_SIGNUPBTN = "SET_SIGNUPBTN";
export const REGISTER_COMPANY = "REGISTER_COMPANY";
export const REGISTER_USER = "REGISTER_USER";
export const AUTHORIZE_SUCCESS = "AUTHORIZE_SUCCESS";
export const LOGIN_USER = "LOGIN_USER";