export const CREATE_PLAN = "CREATE_PLAN";
export const CREATE_PLAN_SUCCESS = "CREATE_PLAN_SUCCESS";
export const CREATE_PLAN_ERROR = "CREATE_PLAN_ERROR";

export const GET_PLANS = "GET_PLANS";
export const GET_PLANS_SUCCESS = "GET_PLANS_SUCCESS";
export const GET_PLANS_ERROR = "GET_PLANS_ERROR";

export const GET_SINGLE_PLAN = "GET_SINGLE_PLAN";
export const GET_SINGLE_PLAN_SUCCESS = "GET_SINGLE_PLAN_SUCCESS";
export const GET_SINGLE_PLAN_ERROR = "GET_SINGLE_PLAN_ERROR";

export const GET_TENOR = "GET_TENOR";
export const GET_TENOR_SUCCESS = "GET_TENOR_SUCCESS";
export const GET_TENOR_ERROR = "GET_TENOR_ERROR";

export const GET_EX_RATES = "GET_EX_RATES";
export const GET_EX_RATES_SUCCESS = "GET_EX_RATES_SUCCESS";
export const GET_EX_RATES_ERROR = "GET_EX_RATES_ERROR";

export const GET_CONTRIB_VAL = "GET_CONTRIB_VAL";
export const GET_CONTRIB_VAL_SUCCESS = "GET_CONTRIB_VAL_SUCCESS";
export const GET_CONTRIB_VAL_ERROR = "GET_CONTRIB_VAL_ERROR";
