export const CREATE_PLAN = "CREATE_PLAN";
export const CREATE_PLAN_SUCCESS = "CREATE_PLAN_SUCCESS";
export const CREATE_PLAN_ERROR = "CREATE_PLAN_ERROR";

export const GET_SINGLE_PLAN = "GET_SINGLE_PLAN";
export const GET_SINGLE_PLAN_SUCCESS = "GET_SINGLE_PLAN_SUCCESS";
export const GET_SINGLE_PLAN_ERROR = "GET_SINGLE_PLAN_ERROR";