export const VERIFY_PHONE = "VERIFY_PHONE";
export const VERIFY_PHONE_SUCCESS = "VERIFY_PHONE_SUCCESS";
export const VERIFY_PHONE_ERROR = "VERIFY_PHONE_ERROR";

export const PUT_CONTACT_DETAILS = "PUT_CONTACT_DETAILS";
export const PUT_CONTACT_DETAILS_SUCCESS = "PUT_CONTACT_DETAILS_SUCCESS";
export const PUT_CONTACT_DETAILS_ERROR = "PUT_CONTACT_DETAILS_ERROR";

export const PUT_PERSONAL_INFO = "PUT_PERSONAL_INFO";
export const PUT_PERSONAL_INFO_SUCCESS = "PUT_PERSONAL_INFO_SUCCESS";
export const PUT_PERSONAL_INFO_ERROR = "PUT_PERSONAL_INFO_ERROR";

export const VALIDATE_PHONE_OTP = "VALIDATE_PHONE_OTP";
export const VALIDATE_PHONE_OTP_SUCCESS = "VALIDATE_PHONE_OTP_SUCCESS";
export const VALIDATE_PHONE_OTP_ERROR = "VALIDATE_PHONE_OTP_ERROR";

export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const VERIFY_ACCOUNT_NO = "VERIFY_ACCOUNT_NO";
export const VERIFY_ACCOUNT_NO_SUCCESS = "VERIFY_ACCOUNT_NO_SUCCESS";
export const VERIFY_ACCOUNT_NO_ERROR = "VERIFY_ACCOUNT_NO_ERROR";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const PUT_PERSONAL_DOCUMENTS = "PUT_PERSONAL_DOCUMENTS";
export const PUT_PERSONAL_DOCUMENTS_SUCCESS = "PUT_PERSONAL_DOCUMENTS_SUCCESS";
export const PUT_PERSONAL_DOCUMENTS_ERROR = "PUT_PERSONAL_DOCUMENTS_ERROR";
