export const GET_WALLET_BALANCE = "GET_WALLET_BALANCE";
export const GET_WALLET_BALANCE_SUCCESS = "GET_WALLET_BALANCE_SUCCESS";
export const GET_WALLET_BALANCE_ERROR = "GET_WALLET_BALANCE_ERROR";

export const GET_WALLET_TRANSACTIONS = "GET_WALLET_TRANSACTIONS";
export const GET_WALLET_TRANSACTIONS_SUCCESS = "GET_WALLET_TRANSACTIONS_SUCCESS";
export const GET_WALLET_TRANSACTIONS_ERROR = "GET_WALLET_TRANSACTIONS_ERROR";

export const CLEAR_TRANSACTIONS = "CLEAR_TRANSACTIONS";

export const CLEAR_WALLET_BALANCE = "CLEAR_WALLET_BALANCE";

export const REQUEST_WITHDRAWAL = "REQUEST_WITHDRAWAL"; 
export const REQUEST_WITHDRAWAL_SUCCESS = "REQUEST_WITHDRAWAL_SUCCESS"; 
export const REQUEST_WITHDRAWAL_ERROR = "REQUEST_WITHDRAWAL_ERROR"; 