export const POST_FEEDBACK = "POST_FEEDBACK";
export const POST_FEEDBACK_SUCCESS = "POST_FEEDBACK_SUCCESS";
export const POST_FEEDBACK_ERROR = "POST_FEEDBACK_ERROR";

export const GET_TICKETS = "GET_TICKETS";
export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS";
export const GET_TICKETS_ERROR = "GET_TICKETS_ERROR";

export const GET_SINGLE_TICKET = "GET_SINGLE_TICKET";
export const GET_SINGLE_TICKET_SUCCESS = "GET_SINGLE_TICKET_SUCCESS";
export const GET_SINGLE_TICKET_ERROR = "GET_SINGLE_TICKET_ERROR";

export const GET_OPEN_TICKETS = "GET_OPEN_TICKETS";
export const GET_OPEN_TICKETS_SUCCESS = "GET_OPEN_TICKETS_SUCCESS";
export const GET_OPEN_TICKETS_ERROR = "GET_OPEN_TICKETS_ERROR";

export const GET_CLOSED_TICKETS = "GET_CLOSED_TICKETS";
export const GET_CLOSED_TICKETS_SUCCESS = "GET_CLOSED_TICKETS_SUCCESS";
export const GET_CLOSED_TICKETS_ERROR = "GET_CLOSED_TICKETS_ERROR";