on:
  push:
    branch: main

name: 🚀 Deploy website on push!
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
        
      - name: 🔨 Install Project
        run: npm install
      
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: https://optisoft.com.ng:2083/
          username: ${{ secrets.ftp_name }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/rosabon-treasury.com.ng/
